name: CI (Linux)

on:
  push:
    paths:
      - ".github/workflows/**"
      - "3rdparty/**"
      - "hash/**"
      - "scripts/**"
      - "src/**"
      - "COPYING"
      - "makefile"
  pull_request:
    paths:
      - ".github/workflows/**"
      - "3rdparty/**"
      - "hash/**"
      - "scripts/**"
      - "src/**"
      - "COPYING"
      - "makefile"

permissions:
  contents: read

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc]
        include:
          - compiler: gcc
            cc: gcc
            cxx: g++
            archopts: -U_FORTIFY_SOURCE
            subtarget: f256
            executable: f256
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev libfontconfig-dev libasound2-dev libxinerama-dev libxi-dev qtbase5-dev qtbase5-dev-tools
      - name: Build
        env:
          OVERRIDE_CC: ${{ matrix.cc }}
          OVERRIDE_CXX: ${{ matrix.cxx }}
          ARCHOPTS: ${{ matrix.archopts }}
          SUBTARGET: ${{ matrix.subtarget }}
          TOOLS: 1
        run: make -j3 SUBTARGET=f256 SOURCES=f256/f256.cpp
      - uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.executable }}-linux-${{ matrix.compiler }}-${{ github.sha }}
          path: |
            ${{ matrix.executable }}
            chdman
            unidasm
          if-no-files-found: error
